-- =============================================================================
-- Viber Brawl — COMPLETE DATABASE SETUP, in one file.
--
-- GENERATED by `npm run db:bundle`. Do not edit this file directly.
--
-- How to use it:
--   1. Cloudflare dashboard -> Storage & Databases -> D1 -> your database
--   2. Open the "Console" tab
--   3. Paste this whole file and run it
--
-- It is safe to run more than once: every statement uses IF NOT EXISTS or
-- INSERT OR IGNORE, so it will not duplicate anything or destroy data.
--
-- Migrations included: 0001_init.sql, 0002_catalogues.sql, 0003_rebalance_achievement_xp.sql
-- =============================================================================

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- 0001_init.sql
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- =============================================================================
-- Viber Brawl — accounts, progression, analytics and profiles
-- Migration 0001: initial schema
--
-- Conventions used throughout:
--   * every id is a TEXT uuid (except autoincrement ledger/event rows)
--   * every timestamp is INTEGER unix milliseconds, matching the rest of the
--     project (the Durable Object already uses Date.now())
--   * anything a client could lie about is deliberately absent; every stat here
--     is written by the server from a match it refereed itself
-- =============================================================================

PRAGMA foreign_keys = ON;

-- -----------------------------------------------------------------------------
-- accounts — one row per person. An account may have several ways to sign in.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounts (
  id             TEXT PRIMARY KEY,
  email          TEXT,
  email_verified INTEGER NOT NULL DEFAULT 0,
  status         TEXT    NOT NULL DEFAULT 'active',   -- active | suspended | deleted
  created_at     INTEGER NOT NULL,
  updated_at     INTEGER NOT NULL,
  deleted_at     INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_accounts_email
  ON accounts(lower(email)) WHERE email IS NOT NULL;

-- -----------------------------------------------------------------------------
-- identities — one account, many sign-in methods. This is the model every
-- modern game uses (sign in with Google today, link Discord tomorrow, same
-- account, same progress). Passwords live here too, as provider 'password',
-- so there is exactly one place that knows how to verify a credential.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS identities (
  id            TEXT PRIMARY KEY,
  account_id    TEXT    NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  provider      TEXT    NOT NULL,          -- google | discord | password
  provider_uid  TEXT    NOT NULL,          -- the provider's own user id
  email         TEXT,
  password_hash TEXT,                      -- provider 'password' only
  password_salt TEXT,
  password_algo TEXT,                      -- e.g. pbkdf2-sha256:600000
  created_at    INTEGER NOT NULL,
  last_used_at  INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_identities_provider
  ON identities(provider, provider_uid);
CREATE INDEX IF NOT EXISTS idx_identities_account
  ON identities(account_id);

-- -----------------------------------------------------------------------------
-- profiles — the public-facing half of an account.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profiles (
  account_id         TEXT PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
  display_name       TEXT    NOT NULL,
  display_name_lower TEXT    NOT NULL,
  avatar_viber       TEXT    NOT NULL DEFAULT 'miner',
  country            TEXT,
  is_public          INTEGER NOT NULL DEFAULT 1,
  created_at         INTEGER NOT NULL,
  updated_at         INTEGER NOT NULL,
  name_changed_at    INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_name
  ON profiles(display_name_lower);

-- -----------------------------------------------------------------------------
-- sessions — server-side sessions so a token can actually be revoked.
-- Only a hash of the secret is stored; a database leak does not hand out logins.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sessions (
  id           TEXT PRIMARY KEY,
  account_id   TEXT    NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  token_hash   TEXT    NOT NULL,
  created_at   INTEGER NOT NULL,
  expires_at   INTEGER NOT NULL,
  last_seen_at INTEGER NOT NULL,
  ip_hash      TEXT,
  ua_hash      TEXT,
  revoked_at   INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token_hash);
CREATE INDEX IF NOT EXISTS idx_sessions_account ON sessions(account_id, expires_at);

-- -----------------------------------------------------------------------------
-- guests — a player who has not signed in yet. They can play immediately and
-- upgrade in place later without losing anything. This is the single biggest
-- onboarding win in the whole design.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS guests (
  id           TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  token_hash   TEXT NOT NULL,
  created_at   INTEGER NOT NULL,
  last_seen_at INTEGER NOT NULL,
  claimed_by   TEXT REFERENCES accounts(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_guests_token ON guests(token_hash);

-- -----------------------------------------------------------------------------
-- progress — level and experience. Level is cosmetic prestige ONLY; it never
-- touches a gameplay constant.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS progress (
  account_id    TEXT PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
  level         INTEGER NOT NULL DEFAULT 1,
  xp_total      INTEGER NOT NULL DEFAULT 0,
  xp_into_level INTEGER NOT NULL DEFAULT 0,
  updated_at    INTEGER NOT NULL
);

-- -----------------------------------------------------------------------------
-- player_stats — denormalised career totals for fast profile reads.
-- Fully rebuildable from match_results + xp_ledger; those two are the truth.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS player_stats (
  account_id     TEXT PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
  matches        INTEGER NOT NULL DEFAULT 0,
  wins           INTEGER NOT NULL DEFAULT 0,
  kos            INTEGER NOT NULL DEFAULT 0,
  falls          INTEGER NOT NULL DEFAULT 0,
  dmg_dealt      INTEGER NOT NULL DEFAULT 0,
  dmg_taken      INTEGER NOT NULL DEFAULT 0,
  best_placement INTEGER,
  playtime_s     INTEGER NOT NULL DEFAULT 0,
  current_streak INTEGER NOT NULL DEFAULT 0,
  best_streak    INTEGER NOT NULL DEFAULT 0,
  updated_at     INTEGER NOT NULL
);

-- -----------------------------------------------------------------------------
-- viber_mastery — a separate track per character. Four Vibers means four
-- parallel goals from day one, which is why Apex, Overwatch and League all do it.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS viber_mastery (
  account_id TEXT    NOT NULL,
  char_id    TEXT    NOT NULL,
  xp         INTEGER NOT NULL DEFAULT 0,
  level      INTEGER NOT NULL DEFAULT 1,
  matches    INTEGER NOT NULL DEFAULT 0,
  wins       INTEGER NOT NULL DEFAULT 0,
  kos        INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL,
  PRIMARY KEY (account_id, char_id)
);

-- -----------------------------------------------------------------------------
-- match_summary — one row per completed match, written by the Durable Object.
-- match_id is UNIQUE, and every insert is OR IGNORE, so a Durable Object
-- restart or a retry can never double-count a match.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS match_summary (
  match_id          TEXT PRIMARY KEY,
  room_code         TEXT    NOT NULL,
  map               TEXT,
  ruleset_hash      TEXT,                 -- exact constants used, so old results stay interpretable
  player_count      INTEGER NOT NULL,
  duration_s        INTEGER NOT NULL,
  started_at        INTEGER NOT NULL,
  ended_at          INTEGER NOT NULL,
  winner_player_key TEXT,
  end_reason        TEXT,
  created_at        INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_match_summary_ended ON match_summary(ended_at);

-- -----------------------------------------------------------------------------
-- match_results — one row per player per match. This is the single source of
-- truth for progression and analytics, and it is written by the server, never
-- reported by the client.
--
-- player_key is account_id when signed in, otherwise the guest id, so a guest's
-- results survive their later upgrade to a full account.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS match_results (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  match_id     TEXT    NOT NULL REFERENCES match_summary(match_id) ON DELETE CASCADE,
  player_key   TEXT    NOT NULL,
  account_id   TEXT,
  guest_id     TEXT,
  display_name TEXT    NOT NULL,
  char_id      TEXT    NOT NULL,
  placement    INTEGER NOT NULL,
  lives_left   INTEGER NOT NULL,
  kos          INTEGER NOT NULL,
  falls        INTEGER NOT NULL,
  dmg_dealt    REAL    NOT NULL,
  dmg_taken    REAL    NOT NULL,
  winner       INTEGER NOT NULL DEFAULT 0,
  disconnected INTEGER NOT NULL DEFAULT 0,
  created_at   INTEGER NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_match_results_once
  ON match_results(match_id, player_key);
CREATE INDEX IF NOT EXISTS idx_match_results_player
  ON match_results(player_key, created_at);
CREATE INDEX IF NOT EXISTS idx_match_results_char
  ON match_results(char_id, created_at);

-- -----------------------------------------------------------------------------
-- xp_ledger — append-only. Every XP grant is a row, so a number that looks
-- wrong can always be replayed and explained. The unique index is what makes
-- awards idempotent: the same reason can only ever pay out once per match.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS xp_ledger (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  account_id TEXT    NOT NULL,
  match_id   TEXT,
  amount     INTEGER NOT NULL,
  reason     TEXT    NOT NULL,
  meta_json  TEXT,
  created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_xp_ledger_account
  ON xp_ledger(account_id, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_xp_ledger_once
  ON xp_ledger(account_id, reason, match_id)
  WHERE match_id IS NOT NULL;

-- -----------------------------------------------------------------------------
-- achievements — static catalogue. Tiers and rarity are what make them
-- chaseable rather than a flat checklist.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS achievements (
  id          TEXT PRIMARY KEY,
  name        TEXT    NOT NULL,
  description TEXT    NOT NULL,
  tier        TEXT    NOT NULL DEFAULT 'bronze',  -- bronze | silver | gold | platinum
  secret      INTEGER NOT NULL DEFAULT 0,
  points      INTEGER NOT NULL DEFAULT 0,
  xp_reward   INTEGER NOT NULL DEFAULT 0,
  sort_order  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS account_achievements (
  account_id     TEXT    NOT NULL,
  achievement_id TEXT    NOT NULL REFERENCES achievements(id) ON DELETE CASCADE,
  progress       INTEGER NOT NULL DEFAULT 0,
  unlocked_at    INTEGER,
  PRIMARY KEY (account_id, achievement_id)
);
CREATE INDEX IF NOT EXISTS idx_account_achievements_unlocked
  ON account_achievements(achievement_id, unlocked_at);

-- -----------------------------------------------------------------------------
-- unlocks — COSMETIC ONLY, by construction. `payload_json` describes colours
-- and effects; there is deliberately no column that could hold a gameplay
-- value, and the progression module has no reference to CHAR_STATS at all.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS unlocks (
  id             TEXT PRIMARY KEY,
  kind           TEXT    NOT NULL,   -- palette | skin | ko_effect | trail | banner | title
  name           TEXT    NOT NULL,
  char_id        TEXT,               -- NULL means it applies to any Viber
  source         TEXT    NOT NULL,   -- level | achievement | default
  level_req      INTEGER,
  achievement_id TEXT,
  payload_json   TEXT,
  sort_order     INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS account_unlocks (
  account_id  TEXT    NOT NULL,
  unlock_id   TEXT    NOT NULL REFERENCES unlocks(id) ON DELETE CASCADE,
  source      TEXT    NOT NULL,
  unlocked_at INTEGER NOT NULL,
  PRIMARY KEY (account_id, unlock_id)
);

CREATE TABLE IF NOT EXISTS account_loadout (
  account_id    TEXT PRIMARY KEY,
  equipped_json TEXT    NOT NULL DEFAULT '{}',
  updated_at    INTEGER NOT NULL
);

-- -----------------------------------------------------------------------------
-- challenges — daily and weekly goals, keyed by period so they reset cleanly.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS challenges (
  id          TEXT PRIMARY KEY,
  name        TEXT    NOT NULL,
  description TEXT    NOT NULL,
  period      TEXT    NOT NULL,   -- daily | weekly
  metric      TEXT    NOT NULL,   -- matches | wins | kos | damage | playtime | char_wins
  char_id     TEXT,
  target      INTEGER NOT NULL,
  xp_reward   INTEGER NOT NULL,
  sort_order  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS challenge_progress (
  account_id   TEXT    NOT NULL,
  challenge_id TEXT    NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
  period_key   TEXT    NOT NULL,   -- e.g. 2026-10-05 or 2026-W41
  progress     INTEGER NOT NULL DEFAULT 0,
  claimed_at   INTEGER,
  PRIMARY KEY (account_id, challenge_id, period_key)
);

CREATE TABLE IF NOT EXISTS daily_state (
  account_id        TEXT PRIMARY KEY,
  last_first_win_at INTEGER,
  last_daily_key    TEXT,
  updated_at        INTEGER NOT NULL
);

-- -----------------------------------------------------------------------------
-- events — analytics. Two clearly separated sources:
--   source='server'  authoritative, emitted by the Durable Object
--   source='client'  UX and funnel only, never used for stats or progression
-- schema_version lets the shape change without breaking history.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS events (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  name           TEXT    NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  source         TEXT    NOT NULL,
  account_id     TEXT,
  guest_id       TEXT,
  session_id     TEXT,
  match_id       TEXT,
  room_code      TEXT,
  props_json     TEXT,
  ts             INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_name_ts  ON events(name, ts);
CREATE INDEX IF NOT EXISTS idx_events_account  ON events(account_id, ts);
CREATE INDEX IF NOT EXISTS idx_events_match    ON events(match_id);

-- -----------------------------------------------------------------------------
-- rate_limits — sliding-window counters for auth endpoints. A D1 table is
-- plenty at this scale and avoids another moving part.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rate_limits (
  key          TEXT    NOT NULL,
  window_start INTEGER NOT NULL,
  count        INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (key, window_start)
);

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- 0002_catalogues.sql
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- =============================================================================
-- Migration 0002: static catalogues
--
-- Achievements, cosmetic unlocks and challenges. These are CONTENT, not user
-- data, so they are versioned here and re-applied with OR IGNORE on every
-- migration run. Editing a row here and re-running updates nothing that already
-- exists — to change live content, add a new migration that UPDATEs it.
--
-- Every achievement below is evaluated purely from server-refereed match
-- results, so none of them can be earned by lying to the client.
-- =============================================================================

-- ---------------------------------------------------------------- achievements
INSERT OR IGNORE INTO achievements (id, name, description, tier, secret, points, xp_reward, sort_order) VALUES
  ('first_match',      'First Steps',        'Play your first match.',                                   'bronze',   0,  5,   50,  10),
  ('first_win',        'Last Viber Standing','Win your first match.',                                    'bronze',   0, 10,  100,  20),
  ('first_ko',         'First Blood',        'Land your first knockout.',                                'bronze',   0,  5,   50,  30),
  ('play_10',          'Regular',            'Play 10 matches.',                                         'bronze',   0, 10,  100,  40),
  ('kos_10',           'Brawler',            'Land 10 knockouts.',                                       'bronze',   0, 10,  100,  50),
  ('falls_10',         'Learning Curve',     'Fall off the arena 10 times.',                             'bronze',   0,  5,   50,  60),
  ('damage_500',       'Heavy Hitter',       'Deal 500 total damage.',                                   'bronze',   0, 10,  100,  70),

  ('win_10',           'Contender',          'Win 10 matches.',                                          'silver',   0, 25,  250, 110),
  ('kos_50',           'Enforcer',           'Land 50 knockouts.',                                       'silver',   0, 25,  250, 120),
  ('streak_3',         'On A Roll',          'Win 3 matches in a row.',                                  'silver',   0, 25,  250, 130),
  ('flawless',         'Untouched',          'Win a match without losing a single stock.',               'silver',   0, 30,  300, 140),
  ('comeback',         'Down To The Wire',   'Win a match after being down to your last stock.',         'silver',   0, 30,  300, 150),
  ('no_fall_win',      'Sure Footed',        'Win a match without falling off the arena.',               'silver',   0, 25,  250, 160),
  ('damage_5000',      'Devastator',         'Deal 5,000 total damage.',                                 'silver',   0, 25,  250, 170),
  ('all_vibers_played','Jack Of All Vibers', 'Play a match as each of the four Vibers.',                 'silver',   0, 25,  250, 180),

  ('win_50',           'Champion',           'Win 50 matches.',                                          'gold',     0, 60,  600, 210),
  ('kos_500',          'Knockout Artist',    'Land 500 knockouts.',                                      'gold',     0, 60,  600, 220),
  ('streak_5',         'Unstoppable',        'Win 5 matches in a row.',                                  'gold',     0, 60,  600, 230),
  ('all_vibers_win',   'Master Of All',      'Win a match with each of the four Vibers.',                'gold',     0, 70,  700, 240),
  ('mastery_10_any',   'Dedicated',          'Reach mastery level 10 with any Viber.',                   'gold',     0, 50,  500, 250),
  ('level_25',         'Seasoned',           'Reach account level 25.',                                  'gold',     0, 60,  600, 260),
  ('level_50',         'Veteran',            'Reach account level 50.',                                  'gold',     0, 80,  800, 270),

  ('win_100',          'Legend Of The Arena','Win 100 matches.',                                         'platinum', 0, 150, 1500, 310),
  ('kos_2000',         'Apex Predator',      'Land 2,000 knockouts.',                                    'platinum', 0, 150, 1500, 320),
  ('streak_10',        'Untouchable',        'Win 10 matches in a row.',                                 'platinum', 0, 150, 1500, 330),
  ('mastery_20_all',   'True Master',        'Reach mastery level 20 with every Viber.',                 'platinum', 0, 200, 2000, 340),
  ('level_100',        'Viber Legend',       'Reach account level 100.',                                 'platinum', 0, 250, 2500, 350),

  ('hazard_ko',        'Arena Is Lava',      'Knock someone out with an arena hazard.',                  'silver',   1, 30,  300, 410),
  ('pad_ko',           'Spring Loaded',      'Knock someone out with a spike pad.',                      'silver',   1, 30,  300, 420),
  ('self_hazard',      'Own Worst Enemy',    'Knock yourself out with an arena hazard.',                 'bronze',   1,  5,   50, 430);

-- --------------------------------------------------------------------- unlocks
-- Cosmetic only. `payload_json` carries colours and effect styles. There is no
-- column here that could hold a gameplay value, and nothing in the progression
-- module can read the game's stat tables.
INSERT OR IGNORE INTO unlocks (id, kind, name, char_id, source, level_req, achievement_id, payload_json, sort_order) VALUES
  -- default kit: everyone starts with these
  ('pal_default_miner',  'palette', 'Crimson Standard', 'miner',   'default', NULL, NULL, '{"accent":"#DFF902","body":"#C0392B"}', 10),
  ('pal_default_moss',   'palette', 'Moss Standard',    'moss',    'default', NULL, NULL, '{"accent":"#5CFFE7","body":"#2E7D32"}', 11),
  ('pal_default_volt',   'palette', 'Volt Standard',    'volt',    'default', NULL, NULL, '{"accent":"#FFD36A","body":"#1565C0"}', 12),
  ('pal_default_phantom','palette', 'Phantom Standard', 'phantom', 'default', NULL, NULL, '{"accent":"#A56BFF","body":"#4A148C"}', 13),

  -- level-gated palettes
  ('pal_frost',      'palette', 'Frostbite',     NULL, 'level',  5, NULL, '{"accent":"#B5D4F4","body":"#0C447C"}', 20),
  ('pal_ember',      'palette', 'Ember',         NULL, 'level', 10, NULL, '{"accent":"#FF9F27","body":"#712B13"}', 21),
  ('pal_toxic',      'palette', 'Toxic',         NULL, 'level', 15, NULL, '{"accent":"#97C459","body":"#173404"}', 22),
  ('pal_midnight',   'palette', 'Midnight',      NULL, 'level', 20, NULL, '{"accent":"#7F77DD","body":"#1A1A2E"}', 23),
  ('pal_gold',       'palette', 'Gilded',        NULL, 'level', 30, NULL, '{"accent":"#FAC775","body":"#633806"}', 24),
  ('pal_void',       'palette', 'Void',          NULL, 'level', 50, NULL, '{"accent":"#EEEDFE","body":"#0B0B12"}', 25),

  -- achievement-gated palettes: earned, not ground out
  ('pal_flawless',   'palette', 'Porcelain',     NULL, 'achievement', NULL, 'flawless',        '{"accent":"#FFFFFF","body":"#B4B2A9"}', 30),
  ('pal_champion',   'palette', 'Champion Gold', NULL, 'achievement', NULL, 'win_50',          '{"accent":"#DFF902","body":"#854F0B"}', 31),
  ('pal_legend',     'palette', 'Legend',        NULL, 'achievement', NULL, 'win_100',         '{"accent":"#FF5B5B","body":"#26215C"}', 32),
  ('pal_untouchable','palette', 'Untouchable',   NULL, 'achievement', NULL, 'streak_10',       '{"accent":"#5CFFE7","body":"#04342C"}', 33),

  -- KO effects
  ('ko_default',     'ko_effect', 'Standard Burst', NULL, 'default',     NULL, NULL,             '{"style":"burst","color":"#DFF902"}', 110),
  ('ko_shockwave',   'ko_effect', 'Shockwave',      NULL, 'level',          5, NULL,             '{"style":"shockwave","color":"#5CFFE7"}', 111),
  ('ko_supernova',   'ko_effect', 'Supernova',      NULL, 'level',         25, NULL,             '{"style":"supernova","color":"#FF9F27"}', 112),
  ('ko_shatter',     'ko_effect', 'Shatter',        NULL, 'achievement',   NULL, 'kos_500',        '{"style":"shatter","color":"#A56BFF"}', 113),

  -- trails
  ('trail_default',  'trail', 'Plain Streak',  NULL, 'default',     NULL, NULL,        '{"style":"line","color":"#DFF902"}', 210),
  ('trail_ribbon',   'trail', 'Ribbon',        NULL, 'level',          8, NULL,        '{"style":"ribbon","color":"#5CFFE7"}', 211),
  ('trail_comet',    'trail', 'Comet',         NULL, 'achievement',   NULL, 'streak_3',  '{"style":"comet","color":"#FFD36A"}', 212),
  ('trail_void',     'trail', 'Void Wake',     NULL, 'achievement',   NULL, 'mastery_10_any', '{"style":"void","color":"#7F77DD"}', 213),

  -- banner frames (shown on the profile and the results screen)
  ('banner_default', 'banner', 'Plain',        NULL, 'default',     NULL, NULL,          '{"frame":"plain","pattern":"none"}', 310),
  ('banner_bronze',  'banner', 'Bronze Frame', NULL, 'level',          3, NULL,          '{"frame":"bronze","pattern":"solid"}', 311),
  ('banner_silver',  'banner', 'Silver Frame', NULL, 'level',         12, NULL,          '{"frame":"silver","pattern":"chevron"}', 312),
  ('banner_gold',    'banner', 'Gold Frame',   NULL, 'level',         35, NULL,          '{"frame":"gold","pattern":"chevron"}', 313),
  ('banner_plasma',  'banner', 'Plasma Frame', NULL, 'achievement',   NULL, 'level_50',    '{"frame":"plasma","pattern":"grid"}', 314),

  -- titles
  ('title_rookie',   'title', 'Rookie',        NULL, 'default',     NULL, NULL,           '{"text":"ROOKIE"}', 410),
  ('title_brawler',  'title', 'Brawler',       NULL, 'level',          5, NULL,           '{"text":"BRAWLER"}', 411),
  ('title_contender','title', 'Contender',     NULL, 'achievement',   NULL, 'win_10',       '{"text":"CONTENDER"}', 412),
  ('title_flawless', 'title', 'Untouched',     NULL, 'achievement',   NULL, 'flawless',     '{"text":"UNTOUCHED"}', 413),
  ('title_hammer',   'title', 'Heavy Hitter',  NULL, 'achievement',   NULL, 'damage_5000',  '{"text":"HEAVY HITTER"}', 414),
  ('title_champion', 'title', 'Champion',      NULL, 'achievement',   NULL, 'win_50',       '{"text":"CHAMPION"}', 415),
  ('title_legend',   'title', 'Viber Legend',  NULL, 'achievement',   NULL, 'level_100',    '{"text":"VIBER LEGEND"}', 416),
  ('title_apex',     'title', 'Apex Predator', NULL, 'achievement',   NULL, 'kos_2000',     '{"text":"APEX PREDATOR"}', 417);

-- ------------------------------------------------------------------- challenges
INSERT OR IGNORE INTO challenges (id, name, description, period, metric, char_id, target, xp_reward, sort_order) VALUES
  ('d_win_1',    'Daily Victory',   'Win 1 match',                  'daily',  'wins',     NULL,     1,  150, 10),
  ('d_kos_5',    'Daily Brawler',   'Land 5 knockouts',             'daily',  'kos',      NULL,     5,  120, 11),
  ('d_play_3',   'Daily Warmup',    'Play 3 matches',               'daily',  'matches',  NULL,     3,  100, 12),
  ('w_win_5',    'Weekly Champion', 'Win 5 matches',                'weekly', 'wins',     NULL,     5,  600, 20),
  ('w_kos_25',   'Weekly Enforcer', 'Land 25 knockouts',            'weekly', 'kos',      NULL,    25,  500, 21),
  ('w_damage',   'Weekly Devastator','Deal 3,000 total damage',     'weekly', 'damage',   NULL,  3000,  500, 22);

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- 0003_rebalance_achievement_xp.sql
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- =============================================================================
-- Migration 0003: rebalance achievement XP
--
-- Why: with the original values, a player's FIRST match paid out more XP from
-- achievements (750) than from actually playing it (320), which shot them to
-- level 7 in one game and made the level number feel worthless. Achievements
-- should be a meaningful bonus on top of play, not the main source of it.
--
-- New shape, by tier:
--     bronze 30   silver 100   gold 350   platinum 1000
-- A first match now lands around level 3-4, which is a strong welcome without
-- making the ladder meaningless.
--
-- This is a data migration, not a code change: the rewards live in the
-- catalogue so they can be retuned without touching the progression module.
-- =============================================================================

UPDATE achievements SET xp_reward = 30   WHERE tier = 'bronze';
UPDATE achievements SET xp_reward = 100  WHERE tier = 'silver';
UPDATE achievements SET xp_reward = 350  WHERE tier = 'gold';
UPDATE achievements SET xp_reward = 1000 WHERE tier = 'platinum';
